
# Cancel Format and Color
TXT_RESET='\e[0m';

# Text Format
TXT_BOLD='\e[1m';
TXT_BOLD_RESET='\e[21m';
TXT_DIM='\e[2m';
TXT_DIM_RESET='\e[22m';
TXT_UNDERLINE='\e[4m';
TXT_UNDERLINE_RESET='\e[24m';
TXT_BLINK='\e[5m';
TXT_BLINK_RESET='\e[25m';
TXT_REVERSE='\e[7m';
TXT_REVERSE_RESET='\e[27m';
TXT_HIDDEN='\e[8m';
TXT_HIDDEN_RESET='\e[28m';

# Text Color
## Default
TXT_FG_DEFAULT='\e[39m';
TXT_BG_DEFAULT='\e[49m';
## Gray Levels
TXT_FG_BLACK='\e[30m';
TXT_BG_BLACK='\e[40m';
TXT_FG_DARK_GRAY='\e[90m';
TXT_BG_DARK_GRAY='\e[100m';
TXT_FG_LIGHT_GRAY='\e[37m';
TXT_BG_LIGHT_GRAY='\e[47m';
TXT_FG_WHITE='\e[97m';
TXT_BG_WHITE='\e[107m';
## Colors
TXT_FG_RED='\e[31m';
TXT_BG_RED='\e[41m';
TXT_FG_LIGHT_RED='\e[91m';
TXT_BG_LIGHT_RED='\e[101m';
TXT_FG_GREEN='\e[32m';
TXT_BG_GREEN='\e[42m';
TXT_FG_LIGHT_GREEN='\e[92m';
TXT_BG_LIGHT_GREEN='\e[102m';
TXT_FG_YELLOW='\e[33m';
TXT_BG_YELLOW='\e[43m';
TXT_FG_LIGHT_YELLOW='\e[93m';
TXT_BG_LIGHT_YELLOW='\e[103m';
TXT_FG_BLUE='\e[34m';
TXT_BG_BLUE='\e[44m';
TXT_FG_LIGHT_BLUE='\e[94m';
TXT_BG_LIGHT_BLUE='\e[104m';
TXT_FG_MAGENTA='\e[35m';
TXT_BG_MAGENTA='\e[45m';
TXT_FG_LIGHT_MAGENTA='\e[95m';
TXT_BG_LIGHT_MAGENTA='\e[105m';
TXT_FG_CYAN='\e[36m';
TXT_BG_CYAN='\e[46m';
TXT_FG_LIGHT_CYAN='\e[96m';
TXT_BG_LIGHT_CYAN='\e[106m';
